@Atlantis.Wallets_HostAddress = http://localhost:5050

GET {{Atlantis.Wallets_HostAddress}}/weatherforecast/
Accept: application/json

GET {{Atlantis.Login_HostAddress}}/status/
Accept: application/json

POST {{Atlantis.Login_HostAddress}}/WalletRegister/
Accept: application/json


###
